/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LangAuthVerifyEmailIndexRouteImport } from './routes/$lang/auth/verify-email/index'
import { Route as LangAuthSignupIndexRouteImport } from './routes/$lang/auth/signup/index'
import { Route as LangAuthSigninIndexRouteImport } from './routes/$lang/auth/signin/index'
import { Route as LangAuthResetPasswordIndexRouteImport } from './routes/$lang/auth/reset-password/index'
import { Route as LangAuthForgotPasswordIndexRouteImport } from './routes/$lang/auth/forgot-password/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAuthVerifyEmailIndexRoute =
  LangAuthVerifyEmailIndexRouteImport.update({
    id: '/$lang/auth/verify-email/',
    path: '/$lang/auth/verify-email/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LangAuthSignupIndexRoute = LangAuthSignupIndexRouteImport.update({
  id: '/$lang/auth/signup/',
  path: '/$lang/auth/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAuthSigninIndexRoute = LangAuthSigninIndexRouteImport.update({
  id: '/$lang/auth/signin/',
  path: '/$lang/auth/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAuthResetPasswordIndexRoute =
  LangAuthResetPasswordIndexRouteImport.update({
    id: '/$lang/auth/reset-password/',
    path: '/$lang/auth/reset-password/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LangAuthForgotPasswordIndexRoute =
  LangAuthForgotPasswordIndexRouteImport.update({
    id: '/$lang/auth/forgot-password/',
    path: '/$lang/auth/forgot-password/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/$lang/': typeof LangIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/auth/forgot-password/': typeof LangAuthForgotPasswordIndexRoute
  '/$lang/auth/reset-password/': typeof LangAuthResetPasswordIndexRoute
  '/$lang/auth/signin/': typeof LangAuthSigninIndexRoute
  '/$lang/auth/signup/': typeof LangAuthSignupIndexRoute
  '/$lang/auth/verify-email/': typeof LangAuthVerifyEmailIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/$lang': typeof LangIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/auth/forgot-password': typeof LangAuthForgotPasswordIndexRoute
  '/$lang/auth/reset-password': typeof LangAuthResetPasswordIndexRoute
  '/$lang/auth/signin': typeof LangAuthSigninIndexRoute
  '/$lang/auth/signup': typeof LangAuthSignupIndexRoute
  '/$lang/auth/verify-email': typeof LangAuthVerifyEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/$lang/': typeof LangIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/auth/forgot-password/': typeof LangAuthForgotPasswordIndexRoute
  '/$lang/auth/reset-password/': typeof LangAuthResetPasswordIndexRoute
  '/$lang/auth/signin/': typeof LangAuthSigninIndexRoute
  '/$lang/auth/signup/': typeof LangAuthSignupIndexRoute
  '/$lang/auth/verify-email/': typeof LangAuthVerifyEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/$lang/'
    | '/api/auth/$'
    | '/$lang/auth/forgot-password/'
    | '/$lang/auth/reset-password/'
    | '/$lang/auth/signin/'
    | '/$lang/auth/signup/'
    | '/$lang/auth/verify-email/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/$lang'
    | '/api/auth/$'
    | '/$lang/auth/forgot-password'
    | '/$lang/auth/reset-password'
    | '/$lang/auth/signin'
    | '/$lang/auth/signup'
    | '/$lang/auth/verify-email'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/$lang/'
    | '/api/auth/$'
    | '/$lang/auth/forgot-password/'
    | '/$lang/auth/reset-password/'
    | '/$lang/auth/signin/'
    | '/$lang/auth/signup/'
    | '/$lang/auth/verify-email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LangIndexRoute: typeof LangIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  LangAuthForgotPasswordIndexRoute: typeof LangAuthForgotPasswordIndexRoute
  LangAuthResetPasswordIndexRoute: typeof LangAuthResetPasswordIndexRoute
  LangAuthSigninIndexRoute: typeof LangAuthSigninIndexRoute
  LangAuthSignupIndexRoute: typeof LangAuthSignupIndexRoute
  LangAuthVerifyEmailIndexRoute: typeof LangAuthVerifyEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/auth/verify-email/': {
      id: '/$lang/auth/verify-email/'
      path: '/$lang/auth/verify-email'
      fullPath: '/$lang/auth/verify-email/'
      preLoaderRoute: typeof LangAuthVerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/auth/signup/': {
      id: '/$lang/auth/signup/'
      path: '/$lang/auth/signup'
      fullPath: '/$lang/auth/signup/'
      preLoaderRoute: typeof LangAuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/auth/signin/': {
      id: '/$lang/auth/signin/'
      path: '/$lang/auth/signin'
      fullPath: '/$lang/auth/signin/'
      preLoaderRoute: typeof LangAuthSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/auth/reset-password/': {
      id: '/$lang/auth/reset-password/'
      path: '/$lang/auth/reset-password'
      fullPath: '/$lang/auth/reset-password/'
      preLoaderRoute: typeof LangAuthResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/auth/forgot-password/': {
      id: '/$lang/auth/forgot-password/'
      path: '/$lang/auth/forgot-password'
      fullPath: '/$lang/auth/forgot-password/'
      preLoaderRoute: typeof LangAuthForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LangIndexRoute: LangIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  LangAuthForgotPasswordIndexRoute: LangAuthForgotPasswordIndexRoute,
  LangAuthResetPasswordIndexRoute: LangAuthResetPasswordIndexRoute,
  LangAuthSigninIndexRoute: LangAuthSigninIndexRoute,
  LangAuthSignupIndexRoute: LangAuthSignupIndexRoute,
  LangAuthVerifyEmailIndexRoute: LangAuthVerifyEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
